import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowRight, Check, Globe, Lock } from 'lucide-react'
import { GithubIcon } from '@/components/brand-icons'
import { BackLink, ProjectHeading, SectionHeader } from '@/components/page-header'
import { ProjectMark } from '@/components/project-mark'
import { Stat, KeyValue } from '@/components/stat'
import { StatusPill } from '@/components/status'
import { Stepper } from '@/components/stepper'
import { Timeline } from '@/components/timeline'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { getLaunch } from '@/lib/data'

export default async function LaunchDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const launch = getLaunch(slug)
  if (!launch) notFound()
  const northstar = slug === 'northstar'
  return <div className="flex flex-col gap-6">
    <BackLink href="/">Discover</BackLink>
    <ProjectHeading mark={<ProjectMark name={launch.name} size={64} />} title={launch.name} meta={<><Badge variant="tag">{launch.ticker}</Badge><StatusPill status={launch.phase} /></>} description={<p className="text-ui text-muted-foreground">{launch.description}</p>} actions={<Button variant="outline" size="sm" render={<Link href="/portfolio" />} nativeButton={false}>View portfolio</Button>} />
    <div className="flex flex-wrap gap-2"><Badge variant="tag-outline"><Globe /> {northstar ? 'northstar.community' : 'Project site'}</Badge><Badge variant="tag-outline"><GithubIcon /> {northstar ? 'northstar-labs' : launch.name}</Badge></div>
    <Card className="lg:grid lg:grid-cols-[1fr_300px] lg:items-center xl:grid-cols-[1fr_330px]"><Stepper steps={[{key:'announced',label:'Announced',state:'done'},{key:'sale',label:'Live sale',state:launch.phase === 'live' ? 'current' : 'todo'},{key:'settlement',label:'Settlement',state:'todo'},{key:'trading',label:'Trading & claims',state:'todo'}]} /><p className="border-t pt-4 text-small text-muted-foreground lg:border-t-0 lg:border-l lg:pt-0 lg:pl-5">This page is permanent. After launch it becomes the {launch.ticker} token page, with price, markets and holders added here.</p></Card>
    <nav className="flex gap-6 overflow-x-auto border-b text-ui font-medium" aria-label="Project sections">{(northstar?['Overview','Tokenomics','Evidence','Participants','Updates']:['Overview','Participants']).map((item,index)=><a key={item} href={`#${item.toLowerCase()}`} className={`shrink-0 pb-3 ${index===0?'border-b-2 border-foreground':'text-muted-foreground'}`}>{item}</a>)}<span className="flex shrink-0 items-center gap-1 pb-3 text-faint"><Lock className="size-3" />Trade · after launch</span></nav>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_280px] xl:grid-cols-[minmax(0,1fr)_360px]"><div className="flex min-w-0 flex-col gap-5">
      <Card id="overview"><h2 className="text-title font-semibold">About</h2><p className="text-body leading-relaxed text-muted-foreground">{northstar ? 'Northstar gives communities a shared place to run proposals, pay contributors and track commitments on Stellar. Groups create a space, set membership rules with Soroban contracts and pay out in any Stellar asset. NSTR is used for governance of the protocol treasury and to stake for hosted spaces.' : launch.description}</p><div className="grid grid-cols-2 gap-4 border-t pt-4 sm:grid-cols-4"><Stat tone="plain" label="Category" value={launch.model} className="[&>span:nth-child(2)]:text-ui" /><Stat tone="plain" label="Network" value="Stellar · Soroban" className="[&>span:nth-child(2)]:text-ui" />{northstar && <><Stat tone="plain" label="Live product" value="Yes" className="[&>span:nth-child(2)]:text-ui" /><Stat tone="plain" label="Founded" value="2024" className="[&>span:nth-child(2)]:text-ui" /></>}</div></Card>
      {northstar && <Card><SectionHeader title="Team" description="Project provided identities and verification" /><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{['Amara Kole','Jonas Reyes','Mei Lin','Daniel Stone'].map((person,index)=><div key={person} className="rounded-xl bg-muted p-3"><span className="grid size-8 place-items-center rounded-full bg-foreground text-xs text-background">{person.split(' ').map(word=>word[0]).join('')}</span><b className="mt-3 block text-ui">{person}</b><span className="text-small text-muted-foreground">{['Co-founder, product','Co-founder, engineering','Soroban contracts','Community'][index]}</span><span className="mt-2 flex items-center gap-1 text-2xs text-ok"><Check className="size-3" />{index===3?'SELF-REPORTED':'VERIFIED'}</span></div>)}</div></Card>}
      {northstar && <Card id="evidence"><SectionHeader title="Evidence" description="Verification is evidence, not endorsement. Each item shows where it comes from." />{['GitHub activity','Soroban contracts','Security audit','Token supply','Domain & stellar.toml','Treasury multisig'].map((item,index)=><div key={item} className="flex items-center justify-between gap-4 border-t py-3 text-ui"><div><b>{item}</b><p className="text-small text-muted-foreground">{['Public repositories and contributor activity','Sale, vesting and verification contracts','Review of sale and vesting contracts','Issuer account locked','Issuer and contacts declared','Signer identities provided by the project'][index]}</p></div><span className="shrink-0 font-mono text-2xs text-ok">{index===5?'PROJECT-PROVIDED':'VERIFIED'}</span></div>)}</Card>}
      {northstar && <Card id="tokenomics"><SectionHeader title="Tokenomics" description={`Total supply 100,000,000 ${launch.ticker}`} /><div className="grid gap-5 md:grid-cols-[180px_1fr]"><div className="grid size-40 place-items-center rounded-full border-[22px] border-lime text-center"><div><span className="block font-mono text-3xs text-faint">FOR SALE</span><b className="text-mid">20%</b></div></div><div>{[['Community sale','20%','20,000,000','25% at TGE, 6 mo linear'],['Ecosystem & grants','25%','25,000,000','48 mo linear'],['Treasury','22%','22,000,000','Governance controlled'],['Team','18%','18,000,000','12 mo cliff, 36 mo linear'],['Liquidity','10%','10,000,000','Unlocked at TGE'],['Advisors','5%','5,000,000','6 mo cliff, 24 mo linear']].map(row=><div key={row[0]} className="grid grid-cols-[1fr_50px_90px] gap-2 border-b py-2 text-small sm:grid-cols-[1fr_50px_90px_1fr]"><b>{row[0]}</b><span>{row[1]}</span><span className="font-mono">{row[2]}</span><span className="col-span-3 text-muted-foreground sm:col-span-1">{row[3]}</span></div>)}</div></div></Card>}
      {northstar && <Card id="updates"><SectionHeader title="Updates" description="Project announcements" /><div className="border-t py-3 text-ui"><b>Sale is 70% filled, settlement timeline confirmed</b><p className="text-small text-muted-foreground">Final allocations will be published on-chain before claims open.</p></div><div className="border-t py-3 text-ui"><b>Audit report published</b><p className="text-small text-muted-foreground">The sale and vesting contracts have been reviewed.</p></div></Card>}
    </div><aside className="flex flex-col gap-4">
      <Card><div className="flex justify-between"><span className="caps">{launch.model}</span><StatusPill status={launch.phase} /></div><strong className="text-stat">{launch.raised}</strong><span className="text-small text-muted-foreground">raised of {launch.target} target</span><Progress value={launch.progress} /><span className="font-mono text-2xs">{launch.progress}% funded</span><div className="grid grid-cols-4 gap-1 text-center font-mono">{['02','14','22','09'].map((value,index)=><div key={index} className="rounded-lg bg-muted p-2"><b>{value}</b><span className="block text-3xs text-faint">{['DAYS','HRS','MIN','SEC'][index]}</span></div>)}</div><div><KeyValue label="Price">0.042 USDC</KeyValue><KeyValue label="Tokens for sale">10,000,000 {launch.ticker}</KeyValue><KeyValue label="Accepted">USDC, XLM</KeyValue><KeyValue label="Allocation">{launch.allocation}</KeyValue><KeyValue label="Commitment range">50 – 3,000 USDC</KeyValue></div></Card>
      <Card><SectionHeader title="Your eligibility" /><p className="text-small text-muted-foreground">Connect with Blux to check wallet eligibility. Reference requirements are shown below.</p>{['Stellar activity ≥ 40','Wallet age ≥ 90 days','No Sybil flag'].map(item=><p key={item} className="flex items-center gap-2 text-small"><Check className="size-3 text-ok" />{item}</p>)}{launch.phase === 'live' ? <Button render={<Link href={`/launch/${slug}/participate`} />} nativeButton={false} className="w-full">Participate <ArrowRight data-icon="inline-end" /></Button> : <Button disabled>Participation opens later</Button>}</Card>
      <Card><SectionHeader title="Launch timeline" /><Timeline entries={[{key:'registration',title:'Registration opened',detail:'Sep 15 · 14:00 UTC',state:'done'},{key:'sale',title:'Sale opened',detail:'Sep 22 · 14:00 UTC',state:'done'},{key:'close',title:'Sale closes',detail:launch.date,state:'current'},{key:'allocation',title:'Final allocations published',detail:'Sep 30 · 14:00 UTC',state:'todo'},{key:'claims',title:'25% claimable',detail:'Oct 02 · 14:00 UTC',state:'todo'}]} /></Card>
      <Card id="participants"><SectionHeader title="Participants" action={<b>{launch.participants}</b>} /><p className="text-small text-muted-foreground">Participation by reputation level is illustrative.</p>{[['Level 5',14],['Level 4',31],['Level 3',38],['Level 2',17]].map(([label,value])=><div key={label} className="flex items-center gap-2 text-small"><span className="w-12">{label}</span><Progress value={Number(value)} /><span>{value}%</span></div>)}</Card>
    </aside></div>
  </div>
}
